version: "3.9"
services:
  webapi:
    build: 
      context: ./src/webapi
      dockerfile: dockerfileDebug
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
  calculator:
    build: ./src/calculator
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development